# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: formatting
        name: Formatting with Racket-fixw
        entry: raco fixw .
        language: system
        pass_filenames: false
